### PR TITLE
Reduce time to package.

### PR DESCRIPTION
**Pull request by temyers**
This PR adds a Docker container for development - to create a consistent development environment for contributions.

Also, since there are no module dependencies in the package.json, this excludes the node_modules folder from all functions.

Speeds up the packaging process.  Based on timings from my local machine, using the Docker container environment:

Before:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Done in 453.07s.
```

After:
```
yarn run v0.24.4
$ serverless package 
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Done in 146.59s.
```

### CODE REVIEW

**Comment by temyers** [comment]
@mikerahmati any changes required?

**Comment by temyers** [comment]
@mikerahmati - anything blocking this from being merged?

**Comment by mikerahmati** [comment]
Thanks @temyers I'll test this, and get back to you

**Comment by keinu** [comment]
Bump

**Comment by sam-doomguy** [comment]
@temyers it's probably the oldest PR I've ever seen! Sorry we haven't been responsive on this.

- Looks like the current version has two dependencies, so we can no longer exclude node_modules/**
- We are planning to switch to Node.js 12.x, you might want to update the Docker Node.js version accordingly

**Pull request closed without merging**
