### PR TITLE
PD-9060 remove mocha

### PR DESCRIPTION
**Pull request by iaindurham**
### Issue Link:

PD-9060

### What does it do?

This was mainly to remove the mocha packages but thought I would spruce things up a bit while I was here....

So here is a collection of package clean up, and improvements. 

Note: There is no functional changes in this PR.

#### Checklist (if applicable)

- [ ] README update - This wasn't required as there is no mention of testing in the Readme

---

#### Notes to reviewers

These changes can be reviewed as a whole, or can be reviewed as individual commits as all the commits are for a single feature/change.

I added a coverage command but as this is a public repo I didn't run the coverage report on push as there is nothing in the Readme about requiring unit tests so didn't want to start enforcing it without consideration and updating the readme docs

### CODE REVIEW

**Review by binli0114 — APPROVED** [review]
lgtm 🎉
Just a reminder, we need to get the QA done before merging it to master.

**Comment by iaindurham** [comment]
@binli0114 There wasn't any changes to any functional code (not even code style changes) so does this need to go through QA? There is nothing for them to test.

**Comment by binli0114** [comment]
> @binli0114 There wasn't any changes to any functional code (not even code style changes) so does this need to go through QA? There is nothing for them to test.

@iaindurham 
Assign it to me, I will do a quick Technical QA for it.

**Comment by iaindurham** [comment]
Technical QA was passed so merging this change

**Pull request merged**
